<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
      <UserSecretsId>f72cd91c-b094-49eb-882c-6283cce5e3b0</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\cts.core.svc.contracts\cts.core.svc.contracts.csproj" />
      <ProjectReference Include="..\cts.core.svc.domain\cts.core.svc.domain.csproj" />
    </ItemGroup>

</Project>
