<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
      <UserSecretsId>ed0a49c5-2185-4fcb-a791-4eac62efd83b</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit.Analyzers" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\cts.core.svc.application\cts.core.svc.application.csproj" />
      <ProjectReference Include="..\cts.core.svc.infrastructure\cts.core.svc.infrastructure.csproj" />
    </ItemGroup>
    
</Project>
