<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Identity.Core" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\cts.core.svc.application\cts.core.svc.application.csproj" />
      <ProjectReference Include="..\cts.core.svc.contracts\cts.core.svc.contracts.csproj" />
      <ProjectReference Include="..\cts.core.svc.domain\cts.core.svc.domain.csproj" />
    </ItemGroup>
    
</Project>
